"""Initial schema

Revision ID: 8578afeae2fc
Revises: 
Create Date: 2026-10-05 22:45:52.748928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8578afeae2fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_capacity', sa.Integer(), nullable=False),
    sa.Column('walk_in_reserve_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('slot_code', sa.String(), nullable=False),
    sa.Column('slot_type', sa.Enum('REGULAR', 'EV', 'ACCESSIBLE', 'VIP', name='slottype'), nullable=False),
    sa.Column('current_status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE', name='slotstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_slots_slot_code'), 'parking_slots', ['slot_code'], unique=True)
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('vehicle_plate', sa.String(), nullable=False),
    sa.Column('slot_type', sa.Enum('REGULAR', 'EV', 'ACCESSIBLE', 'VIP', name='slottype'), nullable=False),
    sa.Column('eta_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eta_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CHECKED_IN', 'EXPIRED', 'CANCELLED', name='reservationstatus'), nullable=False),
    sa.Column('qr_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_eta_window_end'), 'reservations', ['eta_window_end'], unique=False)
    op.create_index(op.f('ix_reservations_eta_window_start'), 'reservations', ['eta_window_start'], unique=False)
    op.create_index(op.f('ix_reservations_qr_token'), 'reservations', ['qr_token'], unique=True)
    op.create_index('ix_reservations_status_time', 'reservations', ['status', 'eta_window_start', 'eta_window_end'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_table('parking_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=True),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_plate', sa.String(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'OVERSTAY', name='sessionstatus'), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['parking_lots.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_sessions_vehicle_plate'), 'parking_sessions', ['vehicle_plate'], unique=False)
    op.create_table('sensor_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('distance_cm', sa.Float(), nullable=False),
    sa.Column('detected_state', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE', name='slotstatus'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_events_recorded_at'), 'sensor_events', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_sensor_events_slot_id'), 'sensor_events', ['slot_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['parking_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_sensor_events_slot_id'), table_name='sensor_events')
    op.drop_index(op.f('ix_sensor_events_recorded_at'), table_name='sensor_events')
    op.drop_table('sensor_events')
    op.drop_index(op.f('ix_parking_sessions_vehicle_plate'), table_name='parking_sessions')
    op.drop_table('parking_sessions')
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index('ix_reservations_status_time', table_name='reservations')
    op.drop_index(op.f('ix_reservations_qr_token'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_eta_window_start'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_eta_window_end'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_parking_slots_slot_code'), table_name='parking_slots')
    op.drop_table('parking_slots')
    op.drop_table('parking_lots')
    # ### end Alembic commands ###
